language: go

go:
  - "1.14"

branches:
  only:
    - master
    - staging
    - develop

install:
  - go version
  - go get -u golang.org/x/lint/golint

jobs:
  include:
    - stage: CI
      script:
        - echo "Hello World"
        - go build .
        - go vet .
        - golint .
        - cd test && go test -v

    - stage: Deploy
      script:
        - echo "Deploy"