language: go

go:
  - "1.14"

branches:
  only:
    - master
    - staging
    - develop

jobs:
  include:
    - stage: CI    
      script:
        - echo "Hello World"
        - go build .
    - script:
        - go vet .
    - install:
        - go get -u golang.org/x/lint/golint
      script:
        - golint .
    - script:
        - cd test && go test -v

    - stage: Deploy
      script:
        - echo "Deploy"