language: go

go:
  - "1.14"

branches:
  only:
    - staging
    - develop

jobs:
  include:
    - stage: CI
      script:
        - echo "Hello World"
        - go build .
        - cd test && go test -v